Add changes on anykernel3 section

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -159,24 +159,62 @@ jobs:
         run: |
           cd ~/AnyKernel3
           cat > anykernel.sh << EOF
+          ### AnyKernel3 Ramdisk Mod Script
+          ## osm0sis @ xda-developers
+          ### AnyKernel setup
+          # global properties
           properties() { '
-          kernel.string=BakaSU android12-5.10 (${kernel_version})
+          kernel.string=GKI with KernelSU by nodsea
           do.devicecheck=0
           do.modules=0
-          do.systemless=1
+          do.systemless=0
           do.cleanup=1
           do.cleanuponabort=0
-          device.name1=X6833B
+          device.name1=
+          device.name2=
+          device.name3=
+          device.name4=
+          device.name5=
           supported.versions=
           supported.patchlevels=
-          '; }
+          supported.vendorpatchlevels=
+          '; } # end properties
 
-          BLOCK=boot;
-          IS_SLOT_DEVICE=1;
+          ### AnyKernel install
+          # boot shell variables
+          BLOCK=boot
+          IS_SLOT_DEVICE=auto
           RAMDISK_COMPRESSION=auto;
           PATCH_VBMETA_FLAG=auto;
+          NO_MAGSIK_CHECK=1
 
-          . tools/ak3-core.sh
+          # import functions/variables and setup patching - see for reference (DO NOT REMOVE)
+          . tools/ak3-core.sh;
+
+          kernel_version=$(cat /proc/version | awk -F '-' '{print $1}' | awk '{print $3}')
+          case $kernel_version in
+          5.1*) ksu_supported=true ;;
+          6.1*) ksu_supported=true ;;
+          6.6*) ksu_supported=true ;;
+          *) ksu_supported=false ;;
+          esac
+
+          ui_print " " "  -> GKI Kernel Supported: $ksu_supported"
+          $ksu_supported || abort "  -> Non-GKI device, abort."
+
+          # boot install
+          split_boot
+          if [ -f "split_img/ramdisk.cpio" ]; then
+          unpack_ramdisk
+          write_boot
+          else
+          flash_boot
+          fi
+
+          ui_print " "
+          ui_print "Testing build"
+          ui_print "Who's gonna tell it"
+          ui_print " "
           EOF
 
       - name: Copy kernel image into AnyKernel3
